### PR TITLE
Generalize Int type

### PR DESCRIPTION
**Pull request by yglukhov**
1. `Int` type is now generic by `static[int]`
2. Added `Int512`, `Int1024` and `Int2048`.
3. `$` simplified a bit.

Requires https://github.com/nim-lang/Nim/pull/7281

### CODE REVIEW

**Review by mratsim — APPROVED** [review]

**Comment by mratsim** [comment]
Note: you missed the uint generalization

**Comment by yglukhov** [comment]
Good point, hold on.

**Comment by yglukhov** [comment]
So I tried and merged UInt and Int procs into a single file. Initially I wanted to use the return type typeclass trick, but it looked too unreliable to me, so in the end there's internal `defineSharedProcs` which is called for `Ints` and `UInts` =)

**Comment by yglukhov** [comment]
After some discussion with @zah, I've generalized it even further.

**Pull request merged**
